version: "3"

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:8000

  db:
    container_name: db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=laravel"
      - "MYSQL_PASSWORD=password"
    volumes:
      - ./docker/db/data:/var/lib/mysql
